### ISSUE TITLE
Instant crash when trying to start Ascom app

### ISSUE THREAD

**Issue by fgoy** [manojkoushik/Arduino_ObservingConditions#1]
After chosing Arduino ObservingConditions in the Ascom dialog box, everytime I press connect, I get a crash box saying that ASCOM.Driver has stopped working. The that ASCOM.DriverConnect stopped working.
I can't seem to be able to get anymore debug info.

**Comment by manojkoushik** [comment]
hmmm....can you check to see that there are no hanging processes in task manager? It will show up as a Test Forms application.

**Comment by fgoy** [comment]
No hanging process as far as i can see. It does it even after a fresh reboot of Windows. The sparkfun board does work, as i tested it with the example code given on the sparkfun webiste.
I'm using the last (6.3) version of Ascom driver. 
Any idea?
Thanks!

**Comment by fgoy** [comment]
Any way to get debug info displaying so I can try to figure out what's happening?
Thanks!

**Comment by fgoy** [comment]
If this can be of any help, here is the ASCOM log : 

19:23:35.072 ObservingConditions       Starting initialisation
19:23:35.093 ObservingConditions       Completed initialisation
19:23:35.172 Connected                 Set {0}  (HEX[53][65][74][20][7B][30][7D])
19:23:35.172 Connected Set             Connecting to port COM4
19:23:35.172 Name Get                  Arduino Observing Conditions
19:23:35.188 Connected                 Get True
19:23:35.188 BoltWoodFile              get TimeStamp
19:23:35.188 BoltWoodFile              get Humidity
19:23:35.209 Description Get           Arduino ObservingConditions
19:23:35.209 DriverInfo Get            Ascom Observing Conditions driver based on Arduino. Version: 6.2
19:23:35.209 DriverVersion Get         6.2
19:23:35.209 InterfaceVersion Get      1
19:23:35.225 Connected                 Set {0}
19:23:35.225 Connected Unset           Disconnecting to port COM4

**Comment by fgoy** [comment]
Found it! My system was set in French - when I switched Windows to English as system language, it worked!
Any idea where it is set in the code to be language specific?
Thanks
